<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MdCsg\MdCsg.csproj" />
    <ProjectReference Include="..\..\src\MdCsg.Gpu\MdCsg.Gpu.csproj" />
  </ItemGroup>

</Project>
