<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MdCsg\MdCsg.csproj" />
    <ProjectReference Include="..\MdCsg.Robust\MdCsg.Robust.csproj" />
    <PackageReference Include="TerraFX.Interop.Windows" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Shaders\*.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
